[package]
name = "chapter3_variables"
version = "0.1.0"
authors = ["Julian Scala <julian.scala@electric.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
